# -*- coding: utf-8 -*-
"""FineTune1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_g4Us14HUmOCTk9PdPcCuWHCpL7ZwCKs

### Pick LLM and Method
"""

pip install wandb

import wandb
wandb.login()

from google.colab import userdata
from huggingface_hub import login
login(token=userdata.get('Huggingface'))

llm_options = {
    "1": {
        "name": "Qwen3-4B",
        "model_id": "unsloth/Qwen3-4B-Instruct-2507",
    },
    "2": {
        "name": "Phi-4-Mini",
        "model_id": "unsloth/Phi-4-mini-instruct-bnb-4bit",
    },
    "3": {
    "name": "Mistral-Nemo-12B",
    "model_id": "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit"
},
    "4": {
        "name": "Llama-3-8B",
        "model_id": "meta-llama/Meta-Llama-3-8B-Instruct",
    },
    "5": {
        "name": "SmolLM2-1.7B",
        "model_id": "unsloth/SmolLM2-1.7B-Instruct-bnb-4bit",
    },
}

print("Which LLM would you like to use?")

for number, llm_data in llm_options.items():
    print(f"{number}. {llm_data['name']}")

while True:
    user_choice = input("Enter your choice: ").strip()

    if user_choice in llm_options:
        selected_llm = llm_options[user_choice]["name"]
        model_id = llm_options[user_choice]["model_id"]
        break

    print("Invalid choice. Please enter 1, 2, 3, or 4.")

print(f"Selected LLM: {selected_llm}")
print(f"Model ID: {model_id}")

fine_tuning_options = {
    "1": "DPO",
    "2": "ORPO",
}

print("\nWhich fine-tuning method would you like to use?")

for number, method_name in fine_tuning_options.items():
    print(f"{number}. {method_name}")

while True:
    user_choice = input("Enter your choice: ").strip()

    if user_choice in fine_tuning_options:
        selected_method = fine_tuning_options[user_choice]
        break

    print("Invalid choice. Please enter 1 or 2.")

print(f"Selected fine-tuning method: {selected_method}")

print(selected_llm)

print(selected_method)

"""### DATASET

#### OLD
"""

import os
import re

folder = "/content/drive/MyDrive/Thesis/TRAIN/OLD/Attack_Tree"

files = [
    filename
    for filename in os.listdir(folder)
    if re.fullmatch(r"at-\d+\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

chosen_old = []

for filename in files:
    filepath = os.path.join(folder, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        attack_tree = f.read().strip()

    chosen_old.append(attack_tree)

print("Number of chosen attack trees:", len(chosen_old))

import os
import re

folder = "/content/drive/MyDrive/Thesis/TRAIN/OLD/Scenario"

files = [
    filename
    for filename in os.listdir(folder)
    if re.fullmatch(r"scenario\d+\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

scenarios_old = []

for filename in files:
    filepath = os.path.join(folder, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        scenario = f.read().strip()

    scenarios_old.append(scenario)

print("Number of scenarios:", len(scenarios_old))

import os
import re

base_rejected_folder = "/content/drive/MyDrive/Thesis/TRAIN/OLD/Rejected"

rejected_folder = f"{base_rejected_folder}/{selected_llm}_rejected"

files = [
    filename
    for filename in os.listdir(rejected_folder)
    if re.fullmatch(r"rejected-\d+\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

rejected_old = []

for filename in files:
    filepath = os.path.join(rejected_folder, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        rejected_tree = f.read().strip()

    rejected_old.append(rejected_tree)

print("Number of rejected attack trees:", len(rejected_old))

"""#### LT"""

import os
import re

attacktree_folder = "/content/drive/MyDrive/Thesis/TRAIN/LT/Attack_Tree"

files = [
    filename
    for filename in os.listdir(attacktree_folder)
    if re.fullmatch(r"attacktree-\d+\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

chosen_LT = []

for filename in files:
    filepath = os.path.join(attacktree_folder, filename)

    #print(filename)

    with open(filepath, "r", encoding="utf-8") as f:
        attack_tree = f.read().strip()

    chosen_LT.append(attack_tree)

print("Number of chosen attack trees:", len(chosen_LT))

import os
import re

base_rejected_folder = "/content/drive/MyDrive/Thesis/TRAIN/LT/Rejected"

rejected_folder = f"{base_rejected_folder}/{selected_llm}_rejected"

files = [
    filename
    for filename in os.listdir(rejected_folder)
    if re.fullmatch(r"rejected-\d+\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

rejected_LT = []

for filename in files:
    filepath = os.path.join(rejected_folder, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        rejected_tree = f.read().strip()

    rejected_LT.append(rejected_tree)

print("Number of rejected attack trees:", len(rejected_LT))

import os
import re

scenario_folder = "/content/drive/MyDrive/Thesis/TRAIN/LT/Scenario"

files = [
    filename
    for filename in os.listdir(scenario_folder)
    if re.fullmatch(r"attacktree-\d+-scenario\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

scenarios_LT = []

for filename in files:
    filepath = os.path.join(scenario_folder, filename)

    #print(filename)

    with open(filepath, "r", encoding="utf-8") as f:
        scenario = f.read().strip()

    scenarios_LT.append(scenario)

print("Number of scenarios:", len(scenarios_LT))

"""#### HT"""

import os
import re

attacktree_folder = "/content/drive/MyDrive/Thesis/TRAIN/HT/Attack_Tree"

files = [
    filename
    for filename in os.listdir(attacktree_folder)
    if re.fullmatch(r"attacktree-\d+\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

chosen_HT = []

for filename in files:
    filepath = os.path.join(attacktree_folder, filename)

    # print(filename)

    with open(filepath, "r", encoding="utf-8") as f:
        attack_tree = f.read().strip()

    chosen_HT.append(attack_tree)

print("Number of chosen attack trees:", len(chosen_HT))

import os
import re

base_rejected_folder = "/content/drive/MyDrive/Thesis/TRAIN/HT/Rejected"

rejected_folder = f"{base_rejected_folder}/{selected_llm}_rejected"

files = [
    filename
    for filename in os.listdir(rejected_folder)
    if re.fullmatch(r"rejected-\d+\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

rejected_HT = []

for filename in files:
    filepath = os.path.join(rejected_folder, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        rejected_tree = f.read().strip()

    rejected_HT.append(rejected_tree)

print("Number of rejected attack trees:", len(rejected_HT))

import os
import re

scenario_folder = "/content/drive/MyDrive/Thesis/TRAIN/HT/Scenario"

files = [
    filename
    for filename in os.listdir(scenario_folder)
    if re.fullmatch(r"attacktree-\d+-scenario\.txt", filename, re.IGNORECASE)
]

files = sorted(
    files,
    key=lambda filename: int(re.search(r"\d+", filename).group())
)

scenarios_HT = []

for filename in files:
    filepath = os.path.join(scenario_folder, filename)

    # print(filename)

    with open(filepath, "r", encoding="utf-8") as f:
        scenario = f.read().strip()

    scenarios_HT.append(scenario)

print("Number of scenarios:", len(scenarios_HT))

"""#### COMBINE"""

dpo_dataset_dict = {
    "prompt": scenarios_old + scenarios_LT + scenarios_HT,
    "chosen": chosen_old + chosen_LT + chosen_HT,
    "rejected": rejected_old + rejected_LT + rejected_HT,
}

print("Prompts:", len(dpo_dataset_dict["prompt"]))
print("Chosen:", len(dpo_dataset_dict["chosen"]))
print("Rejected:", len(dpo_dataset_dict["rejected"]))



"""### Load Model"""

pip install trl

pip install unsloth

#from transformers import AutoTokenizer, AutoModelForCausalLM
from unsloth import FastLanguageModel
import torch
from transformers import BitsAndBytesConfig
from google.colab import userdata

from transformers import TrainingArguments
from trl import DPOTrainer
from trl import DPOConfig
#from google.colab import userdata
from datasets import load_dataset
from datasets import Dataset
from trl import ORPOConfig, ORPOTrainer
import os
access_token = userdata.get('Huggingface')

#model_id = "unsloth/Qwen3-4B-Instruct-2507"
#model_id= "unsloth/gemma-2-2b-it-bnb-4bit"
#model_id= "unsloth/gemma-4-E2B-it-unsloth-bnb-4bit"
#model_id = "meta-llama/Meta-Llama-3-8B-Instruct"
#access_token = userdata.get('Huggingface')

model, tokenizer = FastLanguageModel.from_pretrained(model_id)
model = FastLanguageModel.get_peft_model(model)

selected_llm

"""## FINE-TUNING"""

if selected_method == 'DPO':

  training_args = DPOConfig(
    output_dir=f"./output/{selected_llm}-{selected_method}",
    beta=0.1,
    bf16=True,
    report_to="wandb",
    run_name=f"{selected_llm}-AttackTree-{selected_method}",
    logging_steps=1,
  )


  dpo_trainer = DPOTrainer(
    model = model,
    ref_model=None,
    args=training_args,
    train_dataset=Dataset.from_dict(dpo_dataset_dict),
    processing_class=tokenizer,
  )

elif selected_method == 'ORPO':
  orpo_trainer = ORPOTrainer(
    model = model,
    train_dataset = Dataset.from_dict(dpo_dataset_dict),
    tokenizer = tokenizer,
    args = ORPOConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        beta = 0.1,
        logging_steps = 1,
        optim = "adamw_8bit",
        lr_scheduler_type = "linear",
        #max_steps = 30, # Change to num_train_epochs = 1 for full training runs
        num_train_epochs = 1,
        output_dir =  selected_llm + "-" + selected_method + "./output/",
        report_to = "wandb", # Use TrackIO/WandB etc
    ),
)

if selected_method == 'DPO':
  dpo_trainer.train()
elif selected_method == 'ORPO':
  orpo_trainer.train()

import pandas as pd
from google.colab import files

# Convert trainer logs to a DataFrame
logs_df = pd.DataFrame(dpo_trainer.state.log_history)

# Save as CSV
log_filename = f"{selected_llm}-AttackTree-{selected_method}-training-logs.csv"
logs_df.to_csv(log_filename, index=False)

# Download
files.download(log_filename)

# Save LoRA adapter locally
adapter_dir = f"/content/{selected_llm}_{selected_method}_adapter"

model.save_pretrained(adapter_dir)
tokenizer.save_pretrained(adapter_dir)

print("Adapter saved to:", adapter_dir)


# Save merged model locally
merged_dir = f"/content/{selected_llm}_{selected_method}_merged"

model.save_pretrained_merged(
    merged_dir,
    tokenizer,
    save_method="merged_16bit",
)

print("Merged model saved to:", merged_dir)

#model.save_pretrained("drakidol-Phi-4-lora_model")
#tokenizer.save_pretrained("drakidol-Phi-4_model")

model.push_to_hub_merged(
    f"ESarp/{selected_llm}-AttackTree-{selected_method}",
    tokenizer,
    save_method="merged_16bit",
)



"""## Inference with Fine-Tuned"""

from unsloth import FastLanguageModel
import torch

model_id = f"ESarp/{selected_llm}-AttackTree-{selected_method}"


model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_id,
    max_seq_length=1024,
    load_in_4bit=True,
)

FastLanguageModel.for_inference(model)

from transformers import logging

logging.set_verbosity_error()

system_prompt = """
You generate attack trees from cybersecurity scenarios.

Rules:

- Use exactly 4 spaces for each hierarchy level.
- Every non-leaf node with multiple children must contain either (AND) or (OR).
- Do not write explanations.
- Do not write paragraphs.
- Put every node on a separate line.
- Preserve the hierarchy using indentation.
- Return only the attack tree.
"""

def generate_attack_tree(scenario):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": scenario},
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            inputs,
            max_new_tokens=1024,
            do_sample=False,
        )

    response = tokenizer.decode(
        outputs[0][inputs.shape[-1]:],
        skip_special_tokens=True,
    )

    return response.strip()


# Folder containing scenario files
input_folder = "/content/Scenarios"

# Folder where outputs will be saved
output_folder = f"/content/{selected_llm}/rejected"

os.makedirs(output_folder, exist_ok=True)


# ============================================================
# 1. Process files named:
#
# attacktree-1-scenario.txt
# attacktree-2-scenario.txt
# ...
#
# Output:
#
# attacktree-1.txt
# attacktree-2.txt
# ...
# ============================================================

for number in range(1, 41):

    input_filename = (
        f"attacktree-{number}-scenario.txt"
    )

    output_filename = (
        f"attacktree-{number}.txt"
    )

    input_path = os.path.join(
        input_folder,
        input_filename
    )

    output_path = os.path.join(
        output_folder,
        output_filename
    )

    if not os.path.exists(input_path):
        print(f"Missing: {input_filename}")
        continue

    with open(input_path, "r", encoding="utf-8") as f:
        scenario = f.read().strip()

    print(
        f"Processing attack tree {number}"
    )

    attack_tree = generate_attack_tree(scenario)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(attack_tree)

    print(f"Saved: {output_filename}")


# ============================================================
# 2. Process files named:
#
# scenario1.txt
# scenario2.txt
# ...
#
# Output:
#
# scenario1-attacktree.txt
# scenario2-attacktree.txt
# ...
# ============================================================

for number in range(1, 41):

    input_filename = (
        f"scenario{number}.txt"
    )

    output_filename = (
        f"scenario{number}-attacktree.txt"
    )

    input_path = os.path.join(
        input_folder,
        input_filename
    )

    output_path = os.path.join(
        output_folder,
        output_filename
    )

    if not os.path.exists(input_path):
        print(f"Missing: {input_filename}")
        continue

    with open(input_path, "r", encoding="utf-8") as f:
        scenario = f.read().strip()

    print(
        f"Processing scenario {number}"
    )

    attack_tree = generate_attack_tree(scenario)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(attack_tree)

    print(f"Saved: {output_filename}")


print("Finished all scenarios.")



import shutil
from google.colab import files


folder_path = f"/content/{selected_llm}/rejected"
zip_path = f"/content/{selected_llm}_{selected_method}"

shutil.make_archive(
    zip_path,
    "zip",
    folder_path
)

files.download(f"{zip_path}.zip")



